# Generated by Django 2.0 on 2017-12-05 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20171205_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='username',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
