# Generated by Django 2.0 on 2017-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20171206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_picture',
            field=models.ImageField(upload_to='user_pics/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='user_pics/'),
        ),
    ]
