# Generated by Django 2.0 on 2017-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20171206_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
